### ISSUE TITLE
PSG playing wrong notes on hardware

### ISSUE THREAD

**Issue by Ralakimus** [Clownacy/Sonic-2-Clone-Driver-v2#4]
[Take a listen here](https://youtu.be/ob2QXR40M6w) (Excuse the poor quality for the hardware audio, because that's the best I can do right now)

It plays fine on Fusion, Regen, and Genesis Plus GX, but on hardware, it plays incorrect notes. I don't even know how this is caused.

I can also confirm this does this to the stock Sonic 1 music as well.

**Comment by Ralakimus** [comment]
Alright, I believe I found the fix for this, since now I got it to not screw up on hardware.

Instead of:
`	lea	(SMPS_psg_input).l,a0
	move.b	d0,(SMPS_psg_input).l
	move.b	d6,(SMPS_psg_input).l`

I did what the original S1 driver did and put this:
`	move.b	d0,(SMPS_psg_input).l
	move.b	d6,(SMPS_psg_input).l`

**Comment by Clownacy** [comment]
I was just looking at that code. That's a pretty old change. Nowdays, I'm aware of outspeeding the 2612, but I never thought about the PSG.
