### ISSUE TITLE
please politely disable interrupts

### ISSUE THREAD

**Issue by NatsumiFox** [Clownacy/Sonic-2-Clone-Driver-v2#7]
You have a nasty bug when loading a Z80 driver. In an incredibly rare chance, an interrupt can happen after z80 is stopped and before the Z80 stop check is cleared, soft locking the entire consol. Worse, once it happens, its consistent (at least on emulators). Please [go here](https://github.com/Clownacy/Sonic-2-Clone-Driver-v2/blob/master/engine/Functions.asm#L6) to disable your interrupts, politely of course

**Comment by Clownacy** [comment]
Oh wow, I never noticed that Sonic 2's `SoundDriverLoad` protects against this. Nice catch, thanks.
